"""Central configuration for supported position strategies."""

from .settings import *  # noqa: F401,F403

__all__ = [
    "BACKTEST_SCAN_FREQUENCY", "BACKTEST_START_DATE", "MAX_PRICE", "MAX_TRADES_EMAIL",
    "MIN_LIQUIDITY_USD", "MIN_NORM_SCORE", "MIN_PRICE", "POSITION_INITIAL_EQUITY",
    "POSITION_MAX_PER_STRATEGY", "POSITION_MAX_TOTAL", "POSITION_PYRAMID_ENABLED",
    "POSITION_PYRAMID_MAX_ADDS", "POSITION_PYRAMID_R_TRIGGER", "POSITION_PYRAMID_SIZE",
    "POSITION_RISK_PER_TRADE_PCT", "REGIME_INDEX", "RS_RANKER_MAX_DAYS",
    "RS_RANKER_RS_THRESHOLD", "RS_RANKER_SECTORS", "RS_RANKER_STOP_ATR_MULT",
    "STRATEGY_PRIORITY", "UNIVERSAL_ADX_MIN", "UNIVERSAL_RS_MIN",
]
